CREATE TABLE BM_CODE_GRP (
    GRP_CD VARCHAR(5),
    GRP_NM VARCHAR(100),
    SORT_ORDER INT,
    IS_USE CHAR(1),
    NOTE VARCHAR(500),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE BM_CODE (
    GRP_CD VARCHAR(5),
    COM_CD VARCHAR(10),
    CODE_NM VARCHAR(100),
    SORT_ORDER INT,
    IS_USE CHAR(1),
    ATTR_VALUE1 VARCHAR(100),
    ATTR_VALUE2 VARCHAR(100),
    ATTR_VALUE3 VARCHAR(100),
    NOTE VARCHAR(500),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE BM_MENU (
    MENU_CD VARCHAR(10),
    MENU_NM VARCHAR(100),
    PARENT_MENU_CD VARCHAR(10),
    MENU_LEVEL INT,
    SORT_ORDER INT,
    SRC_PATH VARCHAR(200),
    IS_USE CHAR(1),
    NOTE VARCHAR(500),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE BM_AUTHORITY (
    AUTHORITY_CD VARCHAR(5),
    AUTHORITY_NM VARCHAR(100),
    IS_USE CHAR(1),
    NOTE VARCHAR(500),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE BM_AUTHORITY_MENU (
    AUTHORITY_CD VARCHAR(5),
    MENU_CD VARCHAR(10),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE BM_ZIP_CODE (
    SEQ_NO INT,
    ZIP_CD VARCHAR(6),
    ZIP_NM VARCHAR(160),
    CITY VARCHAR(40),
    COUNTRY VARCHAR(40),
    TOWN VARCHAR(40),
    BUILDING VARCHAR(40),
    IS_LAND VARCHAR(40),
    FROM_NO VARCHAR(20),
    TO_NO VARCHAR(20),
    IS_USE CHAR(1),
    OLD_CODE VARCHAR(6)
);

CREATE TABLE HM_PERSON_BASIC (
    EMP_CD VARCHAR(10),
    EMP_NM VARCHAR(30),
    EMP_CN_NM VARCHAR(30),
    EMP_EN_NM VARCHAR(50),
    PASSWORD VARCHAR(30),
    RESIDENT_NO VARCHAR(13),
    JOIN_DATE VARCHAR(8),
    JOIN_CLASS_CD VARCHAR(5),
    POSITION_CD VARCHAR(5),
    DUTY_CD VARCHAR(5),
    LAST_APPOINT_DATE VARCHAR(8),
    POSITION_UPDATED_DATE VARCHAR(8),
    ORG_CD VARCHAR(10),
    JOB_FAMILY_CD VARCHAR(5),
    JOB_CD VARCHAR(5),
    ASSIGNED_TASK VARCHAR(100),
    OFFICE_PHONE1 VARCHAR(4),
    OFFICE_PHONE2 VARCHAR(4),
    OFFICE_PHONE3 VARCHAR(4),
    HOME_PHONE1 VARCHAR(4),
    HOME_PHONE2 VARCHAR(4),
    HOME_PHONE3 VARCHAR(4),
    CELL_PHONE1 VARCHAR(4),
    CELL_PHONE2 VARCHAR(4),
    CELL_PHONE3 VARCHAR(4),
    EMAIL VARCHAR(100),
    RELIGION_CD VARCHAR(5),
    LAST_SCHOOL_NM VARCHAR(50),
    MAJOR_NM VARCHAR(50),
    SCHOOL_CAREER_CD VARCHAR(5),
    HOUSE_KIND_CD VARCHAR(5),
    ZIP_CD VARCHAR(6),
    ADDRESS1 VARCHAR(200),
    ADDRESS2 VARCHAR(200),
    IS_VETERAN_WELFARE     CHAR(1),
    IS_MILITARY_SERVICE CHAR(1),
    BIRTH_DATE VARCHAR(8),
    IS_LUNAR CHAR(1),
    IS_MARRIAGE CHAR(1),
    HOPPY VARCHAR(100),
    TALENT VARCHAR(200),
    RETIRE_REASON VARCHAR(100),
    IMAGE_PATH VARCHAR(200),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE HM_PERSON_FAMILY (
    EMP_CD VARCHAR(10),
    SEQ INT,
    RELATIONSHIP VARCHAR(20),
    FAMILY_NM VARCHAR(30),
    RESIDENT_NO VARCHAR(13),
    JOB VARCHAR(50),
    IS_CORESIDENCE CHAR(1),
    IS_SUPPORT CHAR(1),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE HM_PERSON_PROJECT (
    EMP_CD VARCHAR(10),
    SEQ INT,
    PROJECT_NM VARCHAR(100),
    PROJECT_DESC VARCHAR(200),
    START_DATE VARCHAR(8),
    END_DATE VARCHAR(8),
    ASSIGNED_TASK VARCHAR(100),
    ORDERING_ORG VARCHAR(100),
    COMPANY VARCHAR(100),
    NOTE VARCHAR(500),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE HM_PERSON_AUTHORITY (
    EMP_CD VARCHAR(10),
    AUTHORITY_CD VARCHAR(5),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE HM_ORGAN_BASIC (
    ORG_CD VARCHAR(10),
    ORG_CLASS_CD VARCHAR(5),
    ORG_NM VARCHAR(100),
    ORG_ALIAS_NM VARCHAR(100),
    ORG_EN_NM VARCHAR(100),
    ORG_EN_ALIAS_NM VARCHAR(100),
    SORT_ORDER INT,
    ORG_LEVEL INT,
    PARENT_ORG_CD VARCHAR(10),
    ORG_BOSS_EMP_CD VARCHAR(10),
    START_DATE VARCHAR(8),
    END_DATE VARCHAR(8),
    NOTE VARCHAR(500),
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);

CREATE TABLE DM_BOARD (
    BOARD_ID INT,
    TITLE VARCHAR(200),
    CONTENT VARCHAR(2000),
    VIEW_COUNT INT,
    CREATED_DATE DATE,
    UPDATED_DATE DATE,
    UPDATED_ID VARCHAR(30),
    UPDATED_IP VARCHAR(30)
);
